### ISSUE TITLE
"macvlan": invalid CIDR : invalid CIDR address:

### ISSUE THREAD

**Issue by jetndra** [moby/libnetwork#2566] opened 2020-06-12 10:08 UTC
Hi I m getting the same error with the below configuration

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
name: cms-oam-eth1
namespace: cms
spec:
config: '{
"cniVersion": "0.3.0",
"type": "macvlan",
"master": "eth0",
"mode": "bridge",
"ipam": {
"type": "host-local",
"datastore": "kubernetes",
"kubernetes": { "kubeconfig": "/etc/cni/net.d/whereabouts.d/whereabouts.kubeconfig" },
"subnet": "192.169.1.0/24",
"rangeStart": "192.169.1.2",
"rangeEnd": "192.169.1.240",
"gateway": "192.169.1.1",
"log_file" : "/tmp/whereabouts.log",
"log_level" : "debug"
}
}
```

```
Normal Scheduled 19s default-scheduler Successfully assigned cms/cms1-0 to k8s-worker-1
Warning FailedCreatePodSandBox 13s kubelet, k8s-worker-1 Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "bdc93dc123701afa226cd844fde27d3c9d20882a0f8c0bd117c4f1381d094df3": Multus: error adding pod to network "cms-oam-eth1": delegateAdd: error invoking DelegateAdd - "macvlan": invalid CIDR : invalid CIDR address:
Warning FailedCreatePodSandBox 6s kubelet, k8s-worker-1 Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "4af83c0247d2fcda83cdf7a53990d84053a89f891839adc7f95a71c7490acec5": Multus: error adding pod to network "cms-oam-eth1": delegateAdd: error invoking DelegateAdd - "macvlan": invalid CIDR : invalid CIDR address:
```

Can anyone plz help how to resolve this issue

**Comment by thaJeztah** [comment] 2020-06-16 11:09
Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](http://dockr.ly/slack)

I'm closing this issue because this is not a bug, but feel free to continue the conversation

**Closed by thaJeztah** 2020-06-16 11:09 UTC
